# Generated by Django 6.0.3 on 2026-05-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='general_notes',
            field=models.TextField(blank=True, help_text='Hair style, preferences, etc.', null=True),
        ),
    ]
